version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
cache:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - "%USERPROFILE%\\.m2"
  - "%USERPROFILE%\\.gradle"
  - "%USERPROFILE%\\.gradle\\wrapper"
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
image:
  - Ubuntu1804
  - Visual Studio 2017
clone_depth: 2
# Only relevant for Linux-based images
stack: jdk 11,docker
build_script:
  - ./gradlew gradleHome downloadDependencies --parallel --refresh-dependencies --stacktrace --build-cache --configure-on-demand --no-daemon 
  - ./gradlew build -x test --parallel --stacktrace --build-cache --configure-on-demand --no-daemon -x check
